"""VMx — hierarchical, lifecycle-aware MVVM viewmodel framework (Python flavor).

Public API is organised by responsibility under sub-packages: ``vmx.lifecycle``,
``vmx.messages``, ``vmx.services``, ``vmx.commands``, ``vmx.components``,
``vmx.composites``, ``vmx.groups``, ``vmx.aggregates``, ``vmx.forwarding``,
``vmx.builders``, ``vmx.tree``, ``vmx.collections``, ``vmx.capabilities``,
``vmx.properties``, ``vmx.localization``, ``vmx.hierarchical``, ``vmx.dialogs``,
``vmx.forms``. The ``vmx.notifications`` sub-package is opt-in and must be
imported explicitly. The full set of public types is re-exported here so
``from vmx import ...`` reaches every primitive.
"""

from vmx.__about__ import __min_spec_version__, __version__
from vmx.aggregates import (
    AggregateVM1,
    AggregateVM1Builder,
    AggregateVM2,
    AggregateVM2Builder,
    AggregateVM3,
    AggregateVM3Builder,
    AggregateVM4,
    AggregateVM4Builder,
    AggregateVM5,
    AggregateVM5Builder,
    AggregateVM6,
    AggregateVM6Builder,
    AggregateVMBuilder1,
    AggregateVMBuilder2,
    AggregateVMBuilder3,
    AggregateVMBuilder4,
    AggregateVMBuilder5,
    AggregateVMBuilder6,
)
from vmx.builders import BuilderValidationError
from vmx.capabilities import (
    ExpandableState,
    Filterable,
    IApprovable,
    ICancelable,
    IClosable,
    ICollapsible,
    IConstructable,
    ICurrentDeletable,
    ICurrentUpdatable,
    IDeletable,
    IDeselectable,
    IDestructable,
    IExpandable,
    IExpansionTogglable,
    IManagable,
    INewCreatable,
    IReconstructable,
    ISavable,
    ISearchable,
    ISelectable,
    ISelectionTogglable,
    IUpdatable,
    Pageable,
    SearchableState,
)
from vmx.collections import (
    BatchUpdateHandle,
    CollectionChangedEvent,
    ObservableDictionary,
    ObservableList,
    PagedComposition,
    ServicedObservableCollection,
)
from vmx.commands import (
    Command,
    CompositeCommand,
    ConfirmationDecoratorCommand,
    DecoratorCommand,
    ModeledCrudCommands,
    ParameterizedCommand,
    RelayCommand,
    RelayCommandBuilder,
    RelayCommandOf,
    RelayCommandOfBuilder,
    RelayCommandOfT,
    RelayCommandOfTBuilder,
    confirm,
    confirm_with_dialog_service,
    precede_with,
    succeed_with,
    wrap_with,
)
from vmx.components import (
    ComponentVM,
    ComponentVMBuilder,
    ComponentVMOf,
    ComponentVMOfBuilder,
    ReadonlyComponentVMOf,
    ReadonlyComponentVMOfBuilder,
    ViewModelType,
)
from vmx.composites import (
    CompositeVM,
    CompositeVMBuilder,
    CompositeVMOf,
    CompositeVMOfBuilder,
)
from vmx.dialogs import (
    NULL_DIALOG_SERVICE,
    DialogService,
    FileFilter,
    NotificationSeverity,
    NullDialogService,
)
from vmx.forms import FormVM
from vmx.forwarding import ForwardingComponentVM, ForwardingCompositeVM
from vmx.groups import GroupVM, GroupVMBuilder
from vmx.hierarchical import HierarchicalVM
from vmx.lifecycle import ConstructionStatus, StatusTransitionError
from vmx.localization import NULL_LOCALIZER, ILocalizer, NullLocalizer
from vmx.messages import (
    CollectionChangedMessage,
    ConstructionStatusChangedMessage,
    FormRevertedMessage,
    Message,
    PropertyChangedMessage,
    TreeStructureChange,
    TreeStructureChangedMessage,
    TypedMessage,
    property_value_changed_messages_for,
)
from vmx.properties import DerivedProperty, from_sources
from vmx.services import (
    NULL_DISPATCHER,
    NULL_MESSAGE_HUB,
    MessageHub,
    MessageHubProto,
    NullDispatcher,
    NullMessageHub,
    RxDispatcher,
    null_message_hub_of,
)
from vmx.tree import find, walk, walk_expanded

__all__ = [
    "NULL_DIALOG_SERVICE",
    "NULL_DISPATCHER",
    "NULL_LOCALIZER",
    "NULL_MESSAGE_HUB",
    "AggregateVM1",
    "AggregateVM1Builder",
    "AggregateVM2",
    "AggregateVM2Builder",
    "AggregateVM3",
    "AggregateVM3Builder",
    "AggregateVM4",
    "AggregateVM4Builder",
    "AggregateVM5",
    "AggregateVM5Builder",
    "AggregateVM6",
    "AggregateVM6Builder",
    "AggregateVMBuilder1",
    "AggregateVMBuilder2",
    "AggregateVMBuilder3",
    "AggregateVMBuilder4",
    "AggregateVMBuilder5",
    "AggregateVMBuilder6",
    "BatchUpdateHandle",
    "BuilderValidationError",
    "CollectionChangedEvent",
    "CollectionChangedMessage",
    "Command",
    "ComponentVM",
    "ComponentVMBuilder",
    "ComponentVMOf",
    "ComponentVMOfBuilder",
    "CompositeCommand",
    "CompositeVM",
    "CompositeVMBuilder",
    "CompositeVMOf",
    "CompositeVMOfBuilder",
    "ConfirmationDecoratorCommand",
    "ConstructionStatus",
    "ConstructionStatusChangedMessage",
    "DecoratorCommand",
    "DerivedProperty",
    "DialogService",
    "ExpandableState",
    "FileFilter",
    "Filterable",
    "FormRevertedMessage",
    "FormVM",
    "ForwardingComponentVM",
    "ForwardingCompositeVM",
    "GroupVM",
    "GroupVMBuilder",
    "HierarchicalVM",
    "IApprovable",
    "ICancelable",
    "IClosable",
    "ICollapsible",
    "IConstructable",
    "ICurrentDeletable",
    "ICurrentUpdatable",
    "IDeletable",
    "IDeselectable",
    "IDestructable",
    "IExpandable",
    "IExpansionTogglable",
    "ILocalizer",
    "IManagable",
    "INewCreatable",
    "IReconstructable",
    "ISavable",
    "ISearchable",
    "ISelectable",
    "ISelectionTogglable",
    "IUpdatable",
    "Message",
    "MessageHub",
    "MessageHubProto",
    "ModeledCrudCommands",
    "NotificationSeverity",
    "NullDialogService",
    "NullDispatcher",
    "NullLocalizer",
    "NullMessageHub",
    "ObservableDictionary",
    "ObservableList",
    "Pageable",
    "PagedComposition",
    "ParameterizedCommand",
    "PropertyChangedMessage",
    "ReadonlyComponentVMOf",
    "ReadonlyComponentVMOfBuilder",
    "RelayCommand",
    "RelayCommandBuilder",
    "RelayCommandOf",
    "RelayCommandOfBuilder",
    "RelayCommandOfT",
    "RelayCommandOfTBuilder",
    "RxDispatcher",
    "SearchableState",
    "ServicedObservableCollection",
    "StatusTransitionError",
    "TreeStructureChange",
    "TreeStructureChangedMessage",
    "TypedMessage",
    "ViewModelType",
    "__min_spec_version__",
    "__version__",
    "confirm",
    "confirm_with_dialog_service",
    "find",
    "from_sources",
    "null_message_hub_of",
    "precede_with",
    "property_value_changed_messages_for",
    "succeed_with",
    "walk",
    "walk_expanded",
    "wrap_with",
]

# Lifecycle capabilities are baseline: every core VM trivially satisfies them.
# See spec/14-capabilities.md rule 2 and CAP-020.
IConstructable.register(ComponentVM)
IConstructable.register(ComponentVMOf)
IConstructable.register(ReadonlyComponentVMOf)
IDestructable.register(ComponentVM)
IDestructable.register(ComponentVMOf)
IDestructable.register(ReadonlyComponentVMOf)
IReconstructable.register(ComponentVM)
IReconstructable.register(ComponentVMOf)
IReconstructable.register(ReadonlyComponentVMOf)
